language: elixir
otp_release:
  - 18.3
elixir:
  - 1.2.6
sudo: false
before_script:
  - mix deps.get --only test
script:
  - mix test
deploy:
  provider: heroku
  on:
    branch: master
  api_key:
    secure: BbGi1r3CwvkZXaQK36RSy84L0fn0VufBaj2SLlplgTnxXvLeCH7xhD2XcEOt+n4OaY4Ok6O9Fi9ZYbNCE+tyPNYz5gZBJ52AaGwXA4IBs08y6dRv/wDQhooTHfPIHxjfRLz+YeAY0wEM7vtCZaRvLOA6AMCK3dLFxzScj8t+uLGqD+n8lIzSYjWA6d+aSjo0VE5Tj9Nu20Fv91LyCzJENUWWUmxNrm4tjOV8pPtfwr0FL3S2Ng4U23r0y1qWbBgTV7ir2GBQph94uskfBjfOYxk2qjlIN9SgCyaLc96nvoU5aGPCQoYMEDrRVj26ZsZ7iuZHLVO7Egb7Yqg2i9n5FNmKuS7iqTjxPmlCdKpFA1GaRhYzfm86X9Zr1zZ32/92JrSPLT8zqE1eyA6SSRhwsp5ajXTu722A5ODqqdCkJHnlPtU/Ax/bTEa2oAd07MStCEua2bl67CwMhQacekYy7fIX/ym0y9CElHFhzpsBvx6hJY+5BwcvfaksbwbZ0W5Lphm4OkZUwEhCagSZsPTO3Lakf10wmYM2ZNGVVM7yR8PejLmAiwuYUYW8gNeREdPW0IuH6b77afivGBKmfy2jxe0A80NT5VoDIjXs8MdfnSEfpJpED5OwiIUiXEeJp/MXA+NSplhijmzDKcut/ZHVcnQm4a5lS7wWyyKRl/DmCGU=
